### ISSUE TITLE
AssertionError: pretrained bert file does not exist

### ISSUE THREAD

**Issue by shenshengke701** [WuHuRestaurant/xf_event_extraction2020Top1#32]
**是少下载某个文件了吗？**
Traceback (most recent call last):
  File "train.py", line 225, in <module>
    training(args)
  File "train.py", line 153, in training
    train_base(opt, info_dict, train_examples, dev_info)
  File "train.py", line 43, in train_base
    model = build_model(opt.task_type, opt.bert_dir, **model_para)
  File "/code/src_final/utils/model_utils.py", line 450, in build_model
    model = Role1Extractor(bert_dir=bert_dir,
  File "/code/src_final/utils/model_utils.py", line 188, in __init__
    super(Role1Extractor, self).__init__(bert_dir=bert_dir,
  File "/code/src_final/utils/model_utils.py", line 70, in __init__
    assert os.path.exists(bert_dir) and os.path.exists(config_path), \
AssertionError: pretrained bert file does not exist

**Comment by saisai-ge** [comment]
你需要自己下载Bert模型，然后加到bert_dir这个目录下

**Comment by shenshengke701** [comment]
> 你需要自己下载 Bert 模型，然后加到 bert_dir 这个目录下

咦咦咦咦  确实是下载了 少个文件我误删了没发现 呜呜呜 谢谢您的回答
